FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bookworm

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN install_packages dnsmasq iptables

COPY wifi-to-eth-route.sh ./

CMD ["bash","wifi-to-eth-route.sh"]
